services:
  yocto-builder:
    build:
      context: .
      args:
        USER_ID: ${HOST_UID:-1000}
        GROUP_ID: ${HOST_GID:-1000}
        USER_NAME: ${HOST_USER:-builder}
    image: yocto-builder:latest
    container_name: yocto-build-env
    ports:
      - "127.0.0.1:2222:2222"
      - "127.0.0.1:2323:2323"
      - "127.0.0.1:4444:4444"
    volumes:
      - ./:/home/builder/
    environment:
      - LANG=en_US.UTF-8
      - LC_ALL=en_US.UTF-8
      - HOME=/home/builder
      - DISTRO=vantageos
      # - MACHINE=qemuarm64
    working_dir: /home/builder
    user: "${HOST_UID:-1000}:${HOST_GID:-1000}"
    stdin_open: true
    tty: true
    # my thinkpad died here so i changed limits 32gb and 16gb reservation
    mem_limit: 6G
    mem_reservation: 4G
    deploy:
      resources:
        limits:
          memory: 6G
        reservations:
          memory: 4G
