interface=wlan0
bind-dynamic
listen-address=192.168.88.1
local-service
no-resolv
##test
server=1.1.1.1
server=8.8.8.8
no-hosts
domain-needed
bogus-priv
cache-size=0
#address=/#/192.168.88.1
address=/vantageos.local/192.168.88.1
