DISTRO = "vantageos"
DISTROOVERRIDES = "vantageos"
DISTRO_VERSION = "kici-kici"
SDK_VERSION = "${DISTRO_VERSION}"
# TCLIBC = "musl"

USER_CLASSES = ""
PACKAGE_CLASSES = "package_ipk"
INHERIT_DISTRO = "devshell sstate license remove-libtool create-spdx buildstats"
INHERIT += "${PACKAGE_CLASSES} ${USER_CLASSES} ${INHERIT_DISTRO}"

INIT_MANAGER = "systemd"
VIRTUAL-RUNTIME_network_manager = "systemd-networkd"

DISTRO_FEATURES_DEFAULT = "debuginfod ext2 ipv4 ipv6 systemd usbhost wifi xattr nfs pci vfat seccomp"
GTK2DISTROFEATURES = ""
GTK3DISTROFEATURES = ""

